spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
        
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
      
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:7080/realms/master/protocol/openid-connect/certs'
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
        

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank API Gatewar Application"
    version: "1.0.0"
    
logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG
        
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000